$kind: http-request
url: "{{baseUrl}}/api/authenticate"
method: POST
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "username": "{{login}}",
      "password": "{{password}}",
      "rememberMe": true
    }
scripts:
  - type: afterResponse
    code: |-
      if (pm.response.code === 200) {
        pm.environment.set('jwt', pm.response.json().id_token);
      }
    language: text/javascript
order: 2000
